Repository optimizely/csharp-sdk, pull requests merged in 2020-07, with the labels that each got.

#230 ci: hook fps on travis
  .travis.yml
Labels: :robot: 12 hrs

#237 Feat: Added DatafileAccessToken in ClientConfigHandler to read from App.config
  OptimizelySDK.Tests/App.config
  OptimizelySDK.Tests/ClientConfigHandlerTest.cs
  OptimizelySDK.Tests/OptimizelyFactoryTest.cs
  OptimizelySDK/ClientConfigHandler.cs
  OptimizelySDK/OptimizelyFactory.cs
  README.md
Labels: :robot: 8 hrs

#229 fix(logs): Added and refactored audience and feature variable evaluation logs
  OptimizelySDK.Tests/AudienceConditionsTests/ConditionEvaluationTest.cs
  OptimizelySDK.Tests/DecisionServiceTest.cs
  OptimizelySDK.Tests/OptimizelyTest.cs
  OptimizelySDK.Tests/UtilsTests/ExperimentUtilsTest.cs
  OptimizelySDK.Tests/UtilsTests/ValidatorTest.cs
  OptimizelySDK/AudienceConditions/BaseCondition.cs
  OptimizelySDK/Bucketing/DecisionService.cs
  OptimizelySDK/Optimizely.cs
  OptimizelySDK/Utils/ExperimentUtils.cs
Labels: :robot: 16 hrs
