Repository optimizely/csharp-sdk, pull requests merged in 2023-08, with the labels that each got.

#366 [FSSDK-9551] Add GitHub Issue templates
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/ENHANCEMENT.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#365 [FSSDK-9526] refact: Implements a warning log for polling interval less than 30s
  OptimizelySDK.Tests/ConfigTest/PollingProjectConfigManagerTest.cs
  OptimizelySDK/Config/PollingProjectConfigManager.cs
Labels: enhancement

#367 [FSSDK-8663] chore: General clean up before ticket work
  OptimizelySDK.DemoApp/OptimizelySDK.DemoApp.csproj
  OptimizelySDK.DemoApp/Views/Shared/_Layout.cshtml
  OptimizelySDK.DemoApp/packages.config
  OptimizelySDK.Net35/Properties/AssemblyInfo.cs
  OptimizelySDK.Net40/Properties/AssemblyInfo.cs
  OptimizelySDK.NetStandard16/Properties/AssemblyInfo.cs
  OptimizelySDK.NetStandard20/Properties/AssemblyInfo.cs
  OptimizelySDK.Tests/App.config
  OptimizelySDK.Tests/Properties/AssemblyInfo.cs
  OptimizelySDK.Tests/packages.config
  OptimizelySDK.sln
  OptimizelySDK/Config/HttpProjectConfigManager.cs
  OptimizelySDK/OptimizelyDecisionContext.cs
  OptimizelySDK/Properties/AssemblyInfo.cs
Labels: chore

#368 [FSSDK-9047] doc: Converted all the files into proper md file format
  docs/readme-sync/sdk-reference-guides/csharp-sdk/010 - install-sdk-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/010 -install-sdk-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/020 - initialize-sdk-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/030 - example-usage-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/040 - optimizelyconfig-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/050 - implement-a-user-profile-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/060 - configure-event-dispatcher-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/070 - event-batching-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/080 - customize-logger-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/090 - customize-error-handler-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/100 - pass-in-audience-attributes-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/110 - set-up-notification-listener-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/120 - activate-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/130 - get-enabled-features-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/140 - get-feature-variable-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/150 - get-forced-variation-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/160 - get-variation-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/170 - is-feature-enabled-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/180 - set-forced-variation-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/190 - track-csharp.md
  docs/readme-sync/sdk-reference-guides/csharp-sdk/index.md
Labels: maintenance
